const ORDERS_ACTION_TYPES = {
    FETCH_ORDERS_START: "orders/FETCH_ORDERS_START",
    FETCH_ORDERS_SUCCESS: "orders/FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILED: "orders/FETCH_ORDERS_FAILED",
}

export default ORDERS_ACTION_TYPES;