const USERS_ACTION_TYPES = {
  SIGN_UP_USER: "users/SIGN_UP_USER",
  SIGN_IN_USER: "users/SIGN_IN_USER",
  SET_LOG_IN: "users/SET_LOG_IN",
  CLEAR_USER: "users/CLEAR_USER"
};

export default USERS_ACTION_TYPES;
